In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties.copy


In [4]:
chinese = [random.randint(60, 100) for _ in range(50)]
english = [random.randint(60, 100) for _ in range(50)]
result = [(chinese[x]+english[x]) for x in range(50)]

display(result )

[130,
 140,
 147,
 151,
 165,
 163,
 161,
 184,
 171,
 155,
 179,
 158,
 159,
 138,
 144,
 163,
 182,
 165,
 142,
 171,
 141,
 138,
 143,
 176,
 156,
 153,
 169,
 160,
 164,
 153,
 176,
 154,
 159,
 177,
 154,
 171,
 163,
 152,
 154,
 158,
 178,
 171,
 125,
 186,
 171,
 135,
 172,
 164,
 145,
 164]

In [5]:
chinese = np.random.randint(low= 60, high=100, size=5)
english = np.random.randint(low= 60, high=100, size=5)
result = chinese + english
display(result)

array([169, 146, 127, 196, 193])

In [9]:
stu01 =  np.random.randint(low= 60, high=100, size=(5,5))
print(stu01)

[[77 79 92 92 93]
 [97 97 80 62 68]
 [68 79 97 82 72]
 [70 77 96 80 69]
 [62 68 62 70 80]]


In [10]:

print(np.sum(stu01, axis=0))
print(np.sum(stu01, axis=1))

[374 400 427 386 382]
[433 404 398 392 342]
